
/*
06/10/2020

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function evenFibonacci(maxNumber) {
    let fibArray = [0, 1]
    for (let i = 0; (fibArray[fibArray.length]) < maxNumber; i++) {
        numberOne = BigInt(fibArray[fibArray.length - 1]);
        numberTwo = BigInt(fibArray[fibArray.length - 2]);

        fibArray.push(numberOne + numberTwo)
    }
    console.log(fibArray)
    console.log(fibArray.length)
    console.log(fibArray[fibArray.length - 1])

}

evenFibonacci(100)