
/*
06/10/2020

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function sumEvenFibonacci(maxNumber) {
    const fibArray = [1, 2];
    let numAcum = 0;

    for (let i = 0; (fibArray[fibArray.length - 1]) <= maxNumber; i++) {
        numberOne = (fibArray[fibArray.length - 1]);
        numberTwo = (fibArray[fibArray.length - 2]);

        fibArray.push(numberOne + numberTwo);

    }//for

    for (let j = 0; fibArray[j] < maxNumber; j++) {
        if (fibArray[j] % 2 == 0) {
            numAcum = numAcum + fibArray[j];
        }
    }//for
    console.log(numAcum);//Only for visualization
    return numAcum;
}//sumeEvenFibonacci

sumEvenFibonacci(4000000)